In [1]:
import pandas as pd
import numpy as np  
import streamlit as slt

In [2]:
df = pd.read_csv('incidents.csv')

In [3]:
df.head(5)

,Identifier,Title,Start date,End date,Number of deaths
0,IBD031681,"Food Poisoning, Imo",18/04/2025,18/04/2025,1
1,IBD032064,"Gunmen Kill Man, Benue",31/03/2025,31/03/2025,1
2,IBD032058,"Auto Crash, Lagos",31/03/2025,31/03/2025,1
3,IBD032066,"Stray Bullets, Sokoto",31/03/2025,31/03/2025,1
4,IBD032062,"Lightening Kills Herder, Kaduna",30/03/2025,30/03/2025,1

In [ ]:
 #I Split the 'Title' column into two new columns: 'Incident' and 'State', 
# using the first comma as the separator (n=1). Expand=True ensures the split 
# results are placed into separate columns.

df[["Incident","State"]] = df["Title"].str.split(",", n=1, expand=True)

In [5]:
df.head(5)

,Identifier,Title,Start date,End date,Number of deaths,Incident,State
0,IBD031681,"Food Poisoning, Imo",18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,"Gunmen Kill Man, Benue",31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,"Auto Crash, Lagos",31/03/2025,31/03/2025,1,Auto Crash,Lagos
3,IBD032066,"Stray Bullets, Sokoto",31/03/2025,31/03/2025,1,Stray Bullets,Sokoto
4,IBD032062,"Lightening Kills Herder, Kaduna",30/03/2025,30/03/2025,1,Lightening Kills Herder,Kaduna

In [ ]:
# I Showed the total number of missing (NaN/NaT) values in each column of the DataFrame

df.isna().sum()

Identifier           0
Title                0
Start date           0
End date             0
Number of deaths     0
Incident             0
State               17
dtype: int64

In [ ]:
# Remove duplicate rows from the DataFrame to ensure each record is unique

df = df.drop_duplicates()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Title             7485 non-null   object
 2   Start date        7485 non-null   object
 3   End date          7485 non-null   object
 4   Number of deaths  7485 non-null   int64
 5   Incident          7485 non-null   object
 6   State             7468 non-null   object
dtypes: int64(1), object(6)
memory usage: 467.8+ KB

In [ ]:
# I Dropped the 'Title' column from the DataFrame since it's no longer needed

df = df.drop(columns=['Title'])

In [10]:
df.head(3)

,Identifier,Start date,End date,Number of deaths,Incident,State
0,IBD031681,18/04/2025,18/04/2025,1,Food Poisoning,Imo
1,IBD032064,31/03/2025,31/03/2025,1,Gunmen Kill Man,Benue
2,IBD032058,31/03/2025,31/03/2025,1,Auto Crash,Lagos

In [11]:
df["State"] =df["State"].str.strip()

In [ ]:
# Fill missing or empty 'State' values at specific row indices 
# using the predefined Replace_map dictionary to ensure consistency

Replace_map ={ 60:"Delta",  78: "Benue",171:"Edo", 
330: "Imo", 837: "Delta", 857:"Edo", 858:"Lagos",
865:"Kastina", 1768:"FCT Abuja",
1800:"(FCT) Abuja", 2318: "(FCT) Abuja", 2875:"Akwa Ibom", 
2889: "Delta", 2932:"(FCT) Abuja",  3888:"Edo", 5182:"(FCT) Abuja", 
6049:"Jigawa", 6136:"Kaduna" ,
6321:"Lagos", 6884:"Edo"}

for idx , val in Replace_map.items():
    if pd.isna(df.loc[idx, "State"]) or df.loc[idx,"State"].strip() == "":
        df.loc[idx, "State"]  =val

In [13]:
# Standardize all variations of 'FCT/Abuja' in the State column to a single format called
# '(FCT) Abuja'

aso = ['FCT','FCT (Abuja)','FCT, Abuja', 'FCT, (Abuja)','FCT(Abuja)',
'Hamza Musa', 'Vigilantes vs Herders, FCT (Abuja)','Abuja (FCT)', '(Fct) Abuja','(Fct) Abuja',
'Abuja','Fct Abuja','Building Collapse Abuja','fct, (Abuja)','fct (Abuja)',
'Fct Abuja','Fct, ( Abuja)','Fct Abuja'
]

mask = df['State'].isin(aso)
df.loc[mask, 'State'] = '(FCT) Abuja'

In [14]:
# 📝 Clean and standardize State names by correcting typos, removing variations, 
# and replacing inconsistent entries with their proper names

df['State'] = df['State'].replace(['Rivers (Offshore)','Port Harcourt','Bonny','River'], 'Rivers')
df['State'] = df['State'].replace('Bayelsa (Offshore)', 'Bayelsa')
df['State'] = df['State'].replace('Son, Anambra', 'Anambra')
df['State'] = df['State'].replace('Dies, Ogun', 'Ogun')
df['State'] = df['State'].replace(['Worshipper, Delta', 'n','delta'], 'Delta')
df['State'] = df['State'].replace(['Akwa Ibom (Offshore)', 'Uyo','Akwa Ibom'], 'Akwa Ibom')
df['State'] = df['State'].replace('Ondo, Ondo', 'Ondo')
df['State'] = df['State'].replace(['Katsina 2','Katsina 1',' Katisna','Katisna','Katsina'], 'Katsina')
df['State'] = df['State'].replace(['Nasarwa', 'Nasaraawa'], 'Nasarawa')
df['State'] = df['State'].replace('Bornon', 'Borno')
df['State'] = df['State'].replace(['Jigaawa','Jiagawa','Jigiwa'], 'Jigawa')
df['State'] = df['State'].replace(['Kadauna','Kadun'], 'Kaduna')
df['State'] = df['State'].replace(['Anmabra','ANambra'], 'Anambra')
df['State'] = df['State'].replace('Taraba`', 'Taraba')
df['State'] = df['State'].replace('Katisna', 'Katsina')
df['State'] = df['State'].replace('Zamafara', 'Zamfara')
df['State'] = df['State'].replace('Cross RIvers', 'Cross River')
df['State'] = df['State'].replace('Niger State', 'Niger')

In [15]:
# 📝 Clean specific rows in the 'Incident' column by removing unwanted state names 

df.loc[60, "Incident"] = df.loc[60, "Incident"].replace(". Delta", "").strip()
df.loc[78, "Incident"] = df.loc[78, "Incident"].replace(" Benue", "").strip()
df.loc[171, "Incident"] = df.loc[171, "Incident"].replace(" Edo", "").strip()
df.loc[3888, "Incident"] = df.loc[388, "Incident"].replace(". Edo", "").strip()
df.loc[1768, "Incident"] = df.loc[1768, "Incident"].replace(" FCT (Abuja)", "").strip()
df.loc[6049, "Incident"] = df.loc[6049, "Incident"].replace(" Jigawa", "").strip()

In [16]:
# Convert 'Start date' and 'End date' columns to datetime format, 
# allowing mixed formats and coercing invalid entries to NaT
# NaT stands for "Not a Time".

df['Start date'] = pd.to_datetime(df['Start date'],format='mixed', errors='coerce')
df['End date'] = pd.to_datetime(df['End date'],format='mixed', errors='coerce')

In [17]:
# this was used to Display concise summary of the DataFrame including column names, 
# non-null counts, and data types to quickly inspect structure and missing values

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7485 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        7485 non-null   object
 1   Start date        7484 non-null   datetime64[ns]
 2   End date          7484 non-null   datetime64[ns]
 3   Number of deaths  7485 non-null   int64
 4   Incident          7485 non-null   object
 5   State             7485 non-null   object
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 667.4+ KB

In [18]:
#Capitalize each  first letter to capital in the state
df['State'] = df['State'].str.title()

In [19]:
# Replace inconsistent '(Fct) Abuja' entry with the standardized '(FCT) Abuja' 
# in the State column

df['State'] = df['State'].replace("(Fct) Abuja","(FCT) Abuja")

In [20]:
df['State'] = df['State'].replace(['Fct Abuja','Fct, ( Abuja)','fct (Abuja)','Abuja',
'fct (Abuja)','Fct ( Abuja)'],
 '(FCT) Abuja')

df['State'] = df['State'].replace(['Katisna','Kastina'],"Katsina")

In [21]:
#this was done to know state that appeared just once
#I ran this code to be sure the values in my State column didnt appear once
value_counts = df['State'].value_counts()
unique_values = value_counts[value_counts == 1].index

print(unique_values.tolist())

[]

In [22]:
#to count all the state using count and unique
asf = df['State'].nunique()
print(asf, "states")

37 states

In [23]:
# Export the cleaned DataFrame to a CSV file named 'victor.csv' for storage or sharing

df.to_csv('victor.csv')